### ISSUE TITLE
Energy Production and Consumption are missing attributes

### ISSUE THREAD

**Issue by Byter09** [thewestlabs/RNG-SyNC-doc#3]
Hello!

I received my `RNG-SYNC-V3-B32B` today and could immediately get data out of my Renogy Rover. Works flawlessly.

However I noticed an annoying problem: I can not add the power generation and consumption to the energy dashboard.

After looking up why not (home assistant links to this page: https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities), and confirming which attributes are set, it would seem that `state_class: total_increasing` is missing.

I'll see if I can fix that locally, but according to Home Assistant integration developers need to do this.

If there's anything else required of me to help out with this, let me know.

Should I be able to "hotfix" this locally by adding the attribute myself (hopefully without it being overwritten by MQTT messages), I'll add another comment here.

Thanks :)

**Comment by Byter09** [comment]
Okay yes, for anyone else encountering this problem: I added the attribute myself on the developer site for states in Home Assistant and now I was able to add it to the dashboard. I just really hope it's not being overwritten.

**Comment by Byter09** [comment]
I just checked again. The dashboard now complains about the missing state class. So it is in fact being overwritten. I'll try to find a permanent solution.

**Comment by Byter09** [comment]
Okay, I got it working.

For anyone else encountering this problem, here's the fix for Home Assistant:

```yaml
homeassistant:
    customize:
        sensor.<entity-name>_power_consumption_today:
            state_class: "total_increasing"
        sensor.<entity-name>_power_generation_today:
            state_class: "total_increasing"
```

Just replace the sensor names accordingly, restart HA, and it should be good to go.
